name: trip_trek
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/images/
    - assets/icons/

  # To add custom fonts, you can use the following example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\font\Poppins-Italic.ttf
        - asset: assets\font\Poppins-Regular.ttf
        - asset: assets\font\Poppins-SemiBold.ttf
        - asset: assets\font\Poppins-SemiBoldItalic.ttf
        - asset: assets\font\Poppins-Medium.ttf
        - asset: assets\font\Poppins-Bold.ttf
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
